import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Plus, Trash2, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "@/hooks/use-toast";
import { useSupabaseQuery } from "@/hooks/useSupabaseQuery";
import { supabase } from "@/integrations/supabase/client";
import { HybridReferenceInput } from "@/components/preauth/HybridReferenceInput";
import { createPreAuthorizationAtomic, getPreAuthorizationErrorMessage, searchClientSuggestions, updatePreAuthorizationAtomic, type ClientSuggestion } from "@/features/preauth/services/preauthStudio.service";

interface Item { id: string; description: string; quantity: number; unitPrice: number }
interface Props { onBack: () => void; editData?: any }
const makeItem = (): Item => ({ id: crypto.randomUUID(), description: "", quantity: 1, unitPrice: 0 });

export default function PreAuthStudio({ onBack, editData }: Props) {
  const { data: insurers } = useSupabaseQuery("insurance_companies");
  const { data: doctors } = useSupabaseQuery("doctors");
  const { data: procedures } = useSupabaseQuery("procedures");
  const { data: diagnoses } = useSupabaseQuery("diagnosis_codes");
  const { data: templates } = useSupabaseQuery("procedure_templates");
  const { data: catalog } = useSupabaseQuery("preauth_catalog_items");
  const { data: settings } = useSupabaseQuery("system_settings");
  const editing = Boolean(editData);
  const [client, setClient] = useState({ patientId: "", name: "", dob: "", phone: "", email: "", address: "", identifier: "", membership: "" });
  const [insurance, setInsurance] = useState({ id: "", name: "", memberNumber: "", plan: "", policy: "", phone: "", email: "" });
  const [clientSearch, setClientSearch] = useState(""); const [suggestions, setSuggestions] = useState<ClientSuggestion[]>([]); const [showSuggestions, setShowSuggestions] = useState(false);
  const [doctorId, setDoctorId] = useState(""); const [doctorName, setDoctorName] = useState("");
  const [procedureId, setProcedureId] = useState(""); const [procedureName, setProcedureName] = useState("");
  const [diagnosisId, setDiagnosisId] = useState(""); const [diagnosisName, setDiagnosisName] = useState("");
  const [procedureDate, setProcedureDate] = useState(""); const [accommodationDays, setAccommodationDays] = useState<number | "">("");
  const [clinicalNotes, setClinicalNotes] = useState(""); const [approvalNotes, setApprovalNotes] = useState("");
  const [customDiagnosis, setCustomDiagnosis] = useState(""); const [extraDiagnoses, setExtraDiagnoses] = useState<string[]>([]);
  const [templateId, setTemplateId] = useState(""); const [items, setItems] = useState<Item[]>([makeItem()]); const [saveSuggestion, setSaveSuggestion] = useState(true); const [busy, setBusy] = useState(false);

  const provider = useMemo(() => ({ name: settings?.find?.((s: any) => s.key === "provider_name")?.value || "", address: settings?.find?.((s: any) => s.key === "provider_address")?.value || "", phone: settings?.find?.((s: any) => s.key === "provider_phone")?.value || "" }), [settings]);
  const doctorOptions = useMemo(() => (doctors || []).map((x: any) => ({ id: String(x.id), label: String(x.doctor_name || x.name || ""), secondary: x.specialty || undefined })), [doctors]);
  const procedureOptions = useMemo(() => (procedures || []).map((x: any) => ({ id: String(x.id), label: String(x.procedure_name || x.name || ""), secondary: x.code || undefined })), [procedures]);
  const diagnosisOptions = useMemo(() => (diagnoses || []).map((x: any) => ({ id: String(x.id), label: `${x.code} — ${x.description}`, secondary: x.code })), [diagnoses]);

  useEffect(() => {
    if (!editData) return;
    setClient({ patientId: editData.patient_id || "", name: editData.client_name || editData.patient_name || "", dob: editData.client_date_of_birth || "", phone: editData.client_phone || "", email: editData.client_email || "", address: editData.client_address || "", identifier: editData.client_identifier || "", membership: editData.client_membership_number || editData.membership_number || "" });
    setInsurance({ id: editData.insurance_company_id || "", name: editData.insurer_name || "", memberNumber: editData.insurer_member_number || "", plan: editData.insurer_plan_name || "", policy: editData.insurer_policy_reference || "", phone: editData.insurer_phone || "", email: editData.insurer_email || "" });
    setDoctorId(editData.doctor_id || ""); setProcedureId(editData.procedure_id || ""); setDiagnosisId(editData.diagnosis_code_id || "");
    setDoctorName(editData.doctor_name || ""); setProcedureName(editData.procedure_name || ""); setDiagnosisName(editData.diagnosis || ""); setProcedureDate(editData.procedure_date || "");
    setAccommodationDays(editData.accommodation_days ?? ""); setClinicalNotes(editData.clinical_notes || ""); setApprovalNotes(editData.approval_notes || "");
    setExtraDiagnoses(Array.isArray(editData.custom_diagnoses) ? editData.custom_diagnoses : []); setTemplateId(editData.template_id || "");
    void (async () => { const { data } = await (supabase.from("preauth_items") as any).select("id,description,quantity,unit_price").eq("preauth_id", editData.id).order("id"); if (data?.length) setItems(data.map((x: any) => ({ id: String(x.id), description: x.description || "", quantity: Number(x.quantity) || 1, unitPrice: Number(x.unit_price) || 0 }))); })();
  }, [editData]);
  useEffect(() => { const q = clientSearch.trim(); if (!q) { setSuggestions([]); return; } const timer = window.setTimeout(() => { void searchClientSuggestions(q).then(setSuggestions).catch(() => setSuggestions([])); }, 180); return () => window.clearTimeout(timer); }, [clientSearch]);

  const total = useMemo(() => items.reduce((sum, x) => sum + Math.max(0, Number(x.quantity) || 0) * Math.max(0, Number(x.unitPrice) || 0), 0), [items]);
  const updateClient = (patch: Partial<typeof client>) => setClient((x) => ({ ...x, ...patch }));
  const updateInsurance = (patch: Partial<typeof insurance>) => setInsurance((x) => ({ ...x, ...patch }));
  const selectSuggestion = (x: ClientSuggestion) => { updateClient({ patientId: x.id, name: x.client_name, dob: x.date_of_birth || "", phone: x.phone || "", email: x.email || "", address: x.address || "", identifier: x.identifier || "", membership: x.membership_number || "" }); setClientSearch(""); setShowSuggestions(false); };
  const selectInsurer = (id: string) => { const x = (insurers || []).find((i: any) => i.id === id); if (x) updateInsurance({ id, name: x.company_name || "", phone: x.phone || "", email: x.email || "" }); };
  const setHybridReference = (value: string, options: any[], setId: (id: string) => void, setName: (name: string) => void) => { const match = options.find((x: any) => x.label === value); setId(match?.id || ""); setName(value); };
  const selectProcedure = (id: string) => { const x = (procedures || []).find((p: any) => p.id === id); setProcedureId(id); setProcedureName(x?.procedure_name || ""); if (x) setItems([{ ...makeItem(), description: x.procedure_name || "", unitPrice: Number(x.default_tariff) || 0 }]); };
  const selectTemplate = (id: string) => { setTemplateId(id); const t = (templates || []).find((x: any) => x.id === id); if (!t) return; try { const raw = typeof t.items === "string" ? JSON.parse(t.items) : t.items; if (Array.isArray(raw) && raw.length) setItems(raw.map((x: any) => ({ ...makeItem(), description: x.description || "", quantity: Number(x.quantity || 1), unitPrice: Number(x.unitCharge ?? x.unit_price ?? 0) }))); } catch { toast({ title: "Template could not be loaded", variant: "destructive" }); } if (t.procedure_id) selectProcedure(t.procedure_id); if (t.diagnosis_code_id) { const d = (diagnoses || []).find((x: any) => x.id === t.diagnosis_code_id); setDiagnosisId(t.diagnosis_code_id); setDiagnosisName(d ? `${d.code} — ${d.description}` : ""); } };
  const addItem = () => setItems((x) => [makeItem(), ...x]); const removeItem = (id: string) => setItems((x) => x.length === 1 ? x : x.filter((i) => i.id !== id)); const patchItem = (id: string, patch: Partial<Item>) => setItems((x) => x.map((i) => i.id === id ? { ...i, ...patch } : i));
  const addCustomDiagnosis = () => { const v = customDiagnosis.trim(); if (v && !extraDiagnoses.includes(v)) setExtraDiagnoses((x) => [...x, v]); setCustomDiagnosis(""); };

  const submit = async () => { setBusy(true); try {
    if (!client.name.trim()) throw new Error("Client name is required."); if (!insurance.name.trim()) throw new Error("Insurer name is required. You can select one or type it manually.");
    const valid = items.filter((x) => x.description.trim()); if (!valid.length) throw new Error("Add at least one service or charge line."); if (valid.some((x) => Number(x.quantity) <= 0 || Number(x.unitPrice) < 0)) throw new Error("Quantities must be greater than zero and charges cannot be negative.");
    const payload = { patient_id: client.patientId || null, client_name: client.name.trim(), client_date_of_birth: client.dob || null, client_phone: client.phone || null, client_email: client.email || null, client_address: client.address || null, client_identifier: client.identifier || null, client_membership_number: client.membership || null, insurance_company_id: insurance.id || null, insurer_name: insurance.name.trim(), insurer_member_number: insurance.memberNumber || null, insurer_plan_name: insurance.plan || null, insurer_policy_reference: insurance.policy || null, insurer_phone: insurance.phone || null, insurer_email: insurance.email || null, doctor_id: doctorId || null, doctor_name: doctorName || null, procedure_id: procedureId || null, procedure_name: procedureName || null, diagnosis: diagnosisName || null, procedure_date: procedureDate || null, total_cost: total, provider_name: provider.name || null, provider_address: provider.address || null, provider_phone: provider.phone || null, status: editing ? editData.status : "pending", accommodation_days: accommodationDays === "" ? null : Number(accommodationDays), clinical_notes: clinicalNotes.trim() || null, approval_notes: approvalNotes.trim() || null, custom_diagnoses: extraDiagnoses, diagnosis_ids: diagnosisId ? [diagnosisId] : [], template_id: templateId || null };
    const serviceItems = valid.map((x) => ({ description: x.description.trim(), quantity: Number(x.quantity), unit_price: Number(x.unitPrice), amount: Number(x.quantity) * Number(x.unitPrice) }));
    if (editing) await updatePreAuthorizationAtomic(editData.id, payload, serviceItems, "amended"); else await createPreAuthorizationAtomic(payload, serviceItems, saveSuggestion);
    toast({ title: editing ? "Pre-authorization amended" : "Pre-authorization created", description: `Total: ${total.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}` }); onBack();
  } catch (e: any) { toast({ title: "Pre-authorization not saved", description: getPreAuthorizationErrorMessage(e), variant: "destructive" }); } finally { setBusy(false); } };

  const field = (label: string, value: string, onChange: (v: string) => void, placeholder?: string, type = "text") => <div><Label>{label}</Label><Input type={type} className="mt-1" value={value} placeholder={placeholder} onChange={(e) => onChange(e.target.value)} /></div>;
  return <div className="space-y-6 max-w-6xl pb-10">
    <div className="flex items-center gap-3"><Button variant="ghost" size="icon" onClick={onBack}><ArrowLeft className="w-5 h-5" /></Button><div><h1 className="page-title">{editing ? "Amend Pre-Authorization" : "Pre-Authorization Studio"}</h1><p className="page-description">Select known references or type new values without leaving the studio.</p></div></div>
    <div className="stat-card"><div className="flex items-start gap-3"><UserRound className="w-5 h-5 mt-0.5" /><div><h2 className="font-heading font-semibold">Fast hybrid data entry</h2><p className="text-sm text-muted-foreground mt-1">Choose a saved record when available. If it is not listed, type the value manually; CareFlow will not invent a database ID.</p></div></div></div>
    <section className="stat-card space-y-4"><h2 className="font-heading font-semibold">Client / Patient</h2><div className="relative">{field("Search previous client suggestions", clientSearch, (v) => { setClientSearch(v); setShowSuggestions(true); }, "Name, membership number or phone...")} {showSuggestions && suggestions.length > 0 && <div className="absolute z-50 left-0 right-0 mt-1 rounded-md border bg-popover shadow-lg overflow-hidden">{suggestions.map((x) => <button key={x.id} type="button" className="w-full text-left px-3 py-2 hover:bg-muted text-sm" onClick={() => selectSuggestion(x)}><span className="font-medium">{x.client_name}</span><span className="block text-muted-foreground">{x.membership_number || x.phone || "Saved client"}</span></button>)}</div>}</div><div className="grid grid-cols-1 md:grid-cols-2 gap-4">{field("Client name *", client.name, (v) => updateClient({ name: v }), "Full name")} {field("Date of birth", client.dob, (v) => updateClient({ dob: v }), "", "date")} {field("Phone", client.phone, (v) => updateClient({ phone: v }), "Phone number")} {field("Email", client.email, (v) => updateClient({ email: v }), "Email address", "email")} {field("Client/member identifier", client.identifier, (v) => updateClient({ identifier: v }), "National/client identifier")} {field("Membership number", client.membership, (v) => updateClient({ membership: v }), "Membership/card number")}</div>{field("Address", client.address, (v) => updateClient({ address: v }), "Client address")} {!editing && <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={saveSuggestion} onChange={(e) => setSaveSuggestion(e.target.checked)} />Remember this client for future suggestions</label>}</section>
    <section className="stat-card space-y-4"><h2 className="font-heading font-semibold">Insurance / Payer</h2><p className="text-xs text-muted-foreground">Select an insurer or type a request-specific insurer name.</p><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><div><Label>Saved insurer</Label><select className="mt-1 w-full h-9 rounded-md border border-input bg-background px-3 text-sm" value={insurance.id} onChange={(e) => selectInsurer(e.target.value)}><option value="">Select directory insurer...</option>{(insurers || []).filter((x: any) => x.is_active !== false).map((x: any) => <option key={x.id} value={x.id}>{x.company_name}</option>)}</select></div>{field("Insurer name *", insurance.name, (v) => updateInsurance({ name: v }), "Type insurer if not listed")}{field("Member number", insurance.memberNumber, (v) => updateInsurance({ memberNumber: v }))}{field("Plan / product", insurance.plan, (v) => updateInsurance({ plan: v }))}{field("Policy reference", insurance.policy, (v) => updateInsurance({ policy: v }))}{field("Insurer phone", insurance.phone, (v) => updateInsurance({ phone: v }))}{field("Insurer email", insurance.email, (v) => updateInsurance({ email: v }), "Email", "email")}</div></section>
    <section className="stat-card space-y-4"><h2 className="font-heading font-semibold">Clinical / Request Details</h2><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><div><Label>Procedure template</Label><select className="mt-1 w-full h-9 rounded-md border border-input bg-background px-3 text-sm" value={templateId} onChange={(e) => selectTemplate(e.target.value)}><option value="">No template</option>{(templates || []).map((x: any) => <option key={x.id} value={x.id}>{x.template_name}</option>)}</select></div><HybridReferenceInput label="Procedure" value={procedureName} onChange={(v) => setHybridReference(v, procedureOptions, setProcedureId, setProcedureName)} options={procedureOptions} placeholder="Select or type procedure"/><HybridReferenceInput label="Doctor" value={doctorName} onChange={(v) => setHybridReference(v, doctorOptions, setDoctorId, setDoctorName)} options={doctorOptions} placeholder="Select or type doctor"/><HybridReferenceInput label="Diagnosis" value={diagnosisName} onChange={(v) => setHybridReference(v, diagnosisOptions, setDiagnosisId, setDiagnosisName)} options={diagnosisOptions} placeholder="Select or type diagnosis"/>{field("Procedure date", procedureDate, setProcedureDate, "", "date")}{field("Accommodation days", String(accommodationDays), (v) => setAccommodationDays(v === "" ? "" : Number(v)), "Days", "number")}</div><div><Label>Clinical notes</Label><Textarea className="mt-1" value={clinicalNotes} onChange={(e) => setClinicalNotes(e.target.value)} placeholder="Clinical justification and relevant notes..." /></div><div><Label>Additional diagnosis / text</Label><div className="flex gap-2 mt-1"><Input value={customDiagnosis} onChange={(e) => setCustomDiagnosis(e.target.value)} placeholder="Type another diagnosis or clinical term..." /><Button type="button" variant="outline" onClick={addCustomDiagnosis}>Add</Button></div>{extraDiagnoses.length > 0 && <div className="flex flex-wrap gap-2 mt-2">{extraDiagnoses.map((x) => <button type="button" key={x} className="rounded-full border px-3 py-1 text-xs" onClick={() => setExtraDiagnoses((d) => d.filter((v) => v !== x))}>{x} ×</button>)}</div>}</div></section>
    <section className="stat-card space-y-4"><div className="flex items-center justify-between"><div><h2 className="font-heading font-semibold">Services & Charges</h2><p className="text-xs text-muted-foreground">Use the catalogue for speed or type any charge manually.</p></div><Button type="button" variant="outline" onClick={addItem}><Plus className="w-4 h-4 mr-1" />Add line</Button></div>{items.map((x) => <div key={x.id} className="grid grid-cols-[1fr_90px_130px_40px] gap-2 items-end"><div><Label>Description</Label><Input className="mt-1" value={x.description} onChange={(e) => patchItem(x.id, { description: e.target.value })} placeholder="Service / item" /></div><div><Label>Qty</Label><Input className="mt-1" type="number" min="1" value={x.quantity} onChange={(e) => patchItem(x.id, { quantity: Number(e.target.value) })} /></div><div><Label>Unit charge</Label><Input className="mt-1" type="number" min="0" step="0.01" value={x.unitPrice} onChange={(e) => patchItem(x.id, { unitPrice: Number(e.target.value) })} /></div><Button type="button" variant="ghost" size="icon" onClick={() => removeItem(x.id)}><Trash2 className="w-4 h-4" /></Button>{(catalog || []).length > 0 && <div className="col-span-full"><div className="flex flex-wrap gap-1">{(catalog || []).slice(0, 8).map((c: any) => <button type="button" key={c.id} className="text-xs border rounded px-2 py-1 hover:bg-muted" onClick={() => patchItem(x.id, { description: c.item_name, unitPrice: Number(c.unit_price) || 0 })}>{c.item_name}</button>)}</div></div>}</div>)}<div className="flex justify-end border-t pt-4 text-lg font-semibold">Total: {total.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</div></section>
    <div className="flex justify-end gap-3"><Button variant="outline" onClick={onBack}>Cancel</Button><Button onClick={submit} disabled={busy}>{busy ? "Saving…" : editing ? "Save amendment" : "Create pre-authorization"}</Button></div>
  </div>;
}
