-- Pre-Authorization Studio scope hardening.
-- This module prepares the authorization-request document and email package only.
-- Insurer response, delivery reconciliation and follow-up workflows are outside scope.

DROP TABLE IF EXISTS public.preauthorization_responses;

DO $$
BEGIN
  IF to_regclass('public.preauthorization_submissions') IS NOT NULL THEN
    UPDATE public.preauthorization_submissions
    SET status = 'prepared'
    WHERE status IS NULL OR status <> 'prepared';

    ALTER TABLE public.preauthorization_submissions
      DROP CONSTRAINT IF EXISTS preauthorization_submissions_status_check;

    ALTER TABLE public.preauthorization_submissions
      ADD CONSTRAINT preauthorization_submissions_status_check
      CHECK (status = 'prepared');

    ALTER TABLE public.preauthorization_submissions
      DROP COLUMN IF EXISTS submitted_at,
      DROP COLUMN IF EXISTS delivered_at,
      DROP COLUMN IF EXISTS failure_reason,
      DROP COLUMN IF EXISTS external_reference;
  END IF;
END $$;

DROP TRIGGER IF EXISTS trg_sync_preauth_submission_state ON public.preauthorization_submissions;
DROP FUNCTION IF EXISTS public.sync_preauthorization_submission_state();

COMMENT ON TABLE public.preauthorization_submissions IS
  'Records that a frozen pre-authorization document and email package were prepared for officer handoff. External email sending and insurer responses are outside this module.';
COMMENT ON TABLE public.preauthorization_versions IS
  'Immutable snapshots of pre-authorization documents generated by the Pre-Authorization Studio.';
COMMENT ON TABLE public.preauthorization_audit_events IS
  'Internal audit trail for document preparation and email handoff events.';
