-- Remove legacy broad policies that bypass the permission model.
DROP POLICY IF EXISTS "System insert audit_logs" ON public.audit_logs;
DROP POLICY IF EXISTS "Authenticated insert ledger" ON public.ledger_entries;
DROP POLICY IF EXISTS "Authenticated update ledger" ON public.ledger_entries;
DROP POLICY IF EXISTS "Authenticated delete ledger" ON public.ledger_entries;
DROP POLICY IF EXISTS "Authenticated read ledger" ON public.ledger_entries;
DROP POLICY IF EXISTS "Users can view all profiles" ON public.profiles;

-- Audit log entries are server-generated by SECURITY DEFINER audit triggers.
DROP POLICY IF EXISTS "Authenticated read audit_logs" ON public.audit_logs;
CREATE POLICY "audit_logs_read_permission"
  ON public.audit_logs
  FOR SELECT TO authenticated
  USING (security_internal.current_user_has_permission('audit.read'));

-- Ledger access follows the dedicated ledger permissions.
CREATE POLICY "ledger_read_permission"
  ON public.ledger_entries
  FOR SELECT TO authenticated
  USING (
    security_internal.current_user_has_permission('ledger.read')
    OR security_internal.current_user_has_permission('reports.read')
  );
CREATE POLICY "ledger_insert_permission"
  ON public.ledger_entries
  FOR INSERT TO authenticated
  WITH CHECK (security_internal.current_user_has_permission('ledger.write'));
CREATE POLICY "ledger_update_permission"
  ON public.ledger_entries
  FOR UPDATE TO authenticated
  USING (security_internal.current_user_has_permission('ledger.write'))
  WITH CHECK (security_internal.current_user_has_permission('ledger.write'));
CREATE POLICY "ledger_delete_admin"
  ON public.ledger_entries
  FOR DELETE TO authenticated
  USING (security_internal.current_user_has_any_role(ARRAY['superuser'::app_role, 'admin'::app_role]));

-- Profiles are readable only by the owner or users who manage users.
CREATE POLICY "profiles_select_scoped"
  ON public.profiles
  FOR SELECT TO authenticated
  USING (
    id = (SELECT auth.uid())
    OR security_internal.current_user_has_permission('users.manage')
  );
