/**
 * Pure metric calculators shared by the executive dashboard, schedules, reports and AI services.
 * They accept raw database rows so any page can feed them straight from Supabase queries.
 */
export interface ExecutiveKpis { claimsCount:number; grossSubmitted:number; netSubmitted:number; rejectedAmount:number; paymentsReceived:number; withholdingTax:number; outstanding:number; rejectionRate:number; collectionRate:number; recoveryRate:number; avgSettlementDays:number; settledCount:number; complianceScore:number; }
export interface YearlyMetric { year:number; submitted:number; payments:number; withholdingTax:number; outstanding:number; }
const sum=(rows:any[],key:string)=>rows.reduce((s,r)=>s+Number(r[key]||0),0);
export function calculateOutstanding(grossSubmitted:number,rejected:number,payments:number,withholdingTax:number){return Math.max(0,Number(grossSubmitted||0)-Number(rejected||0)-Number(payments||0)-Number(withholdingTax||0));}
export function resolveOutstandingStatus(paymentEntryCount:number,withholdingTaxEntryCount:number):"actual"|"provisional"{return paymentEntryCount>0&&withholdingTaxEntryCount>0?"actual":"provisional";}
export function resolveAggregateStatus(statuses:Array<"actual"|"provisional">):"actual"|"provisional"{return statuses.length>0&&statuses.every(s=>s==="actual")?"actual":"provisional";}
export function computeExecutiveKpis(claims:any[]=[],payments:any[]=[],withholdingTax:any[]=[]):ExecutiveKpis{
 const rejected=claims.filter(c=>c.status==="rejected"), active=claims.filter(c=>c.status!=="rejected"), netSubmitted=sum(active,"claim_amount"), rejectedAmount=sum(rejected,"claim_amount"), grossSubmitted=netSubmitted+rejectedAmount, paymentsReceived=sum(payments,"amount_paid"), tax=sum(withholdingTax,"tax_amount");
 const durations=claims.filter(c=>c.submitted_at&&c.paid_at).map(c=>(new Date(c.paid_at).getTime()-new Date(c.submitted_at).getTime())/86_400_000).filter(d=>d>=0), rejectionRate=grossSubmitted>0?rejectedAmount/grossSubmitted*100:0;
 return {claimsCount:claims.length,grossSubmitted,netSubmitted,rejectedAmount,paymentsReceived,withholdingTax:tax,outstanding:calculateOutstanding(grossSubmitted,rejectedAmount,paymentsReceived,tax),rejectionRate,collectionRate:grossSubmitted>0?paymentsReceived/grossSubmitted*100:0,recoveryRate:netSubmitted>0?paymentsReceived/netSubmitted*100:0,avgSettlementDays:durations.length?durations.reduce((s,d)=>s+d,0)/durations.length:0,settledCount:durations.length,complianceScore:Math.max(0,Math.min(100,100-rejectionRate*2))};
}
function dateYear(row:any):number|null{const raw=row?.submitted_at||row?.submission_date||row?.payment_date||row?.created_at||row?.paid_at;if(!raw)return null;const d=new Date(raw);return Number.isNaN(d.getTime())?null:d.getFullYear();}
export function rowYear(row:any):number|null{const explicit=Number(row?.claim_year??row?.year);return Number.isFinite(explicit)&&explicit>0?explicit:dateYear(row);}
function rowMonth(row:any):number|null{const explicit=Number(row?.claim_month??row?.month);if(Number.isFinite(explicit)&&explicit>=1&&explicit<=12)return explicit;const raw=row?.payment_date||row?.withholding_tax_date||row?.tax_date||row?.submitted_at||row?.submission_date||row?.created_at||row?.paid_at;if(!raw)return null;const d=new Date(raw);return Number.isNaN(d.getTime())?null:d.getMonth()+1;}
export interface YearlyKpis{year:number;kpis:ExecutiveKpis;preauthCount:number;rejectedCount:number;}
export function computeYearlyKpis(claims:any[]=[],payments:any[]=[],withholdingTax:any[]=[],preauths:any[]=[]):YearlyKpis[]{const years=new Set<number>();[claims,payments,withholdingTax,preauths].forEach(rows=>rows.forEach(r=>{const y=rowYear(r);if(y)years.add(y);}));return [...years].sort((a,b)=>b-a).map(year=>({year,kpis:computeExecutiveKpis(claims.filter(c=>rowYear(c)===year),payments.filter(p=>rowYear(p)===year),withholdingTax.filter(t=>rowYear(t)===year)),preauthCount:preauths.filter(p=>rowYear(p)===year).length,rejectedCount:claims.filter(c=>rowYear(c)===year&&c.status==="rejected").length}));}
export function buildYearlyMetrics(claims:any[]=[],payments:any[]=[],withholdingTax:any[]=[]):YearlyMetric[]{const years=new Set<number>();[...claims,...payments,...withholdingTax].forEach(r=>{const y=rowYear(r);if(y)years.add(y);});return [...years].sort((a,b)=>b-a).map(year=>{const yearClaims=claims.filter(c=>rowYear(c)===year),submitted=sum(yearClaims,"claim_amount"),rejected=sum(yearClaims.filter(c=>c.status==="rejected"),"claim_amount"),paid=sum(payments.filter(p=>rowYear(p)===year),"amount_paid"),tax=sum(withholdingTax.filter(t=>rowYear(t)===year),"tax_amount");return {year,submitted,payments:paid,withholdingTax:tax,outstanding:calculateOutstanding(submitted,rejected,paid,tax)};});}
export const MONTH_LABELS=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
export interface TrendPoint{month:string;submitted:number;paid:number;rejected:number;withholdingTax:number;outstanding:number;}
export function buildTrendSeries(claims:any[]=[],payments:any[]=[],withholdingTax:any[]=[]):TrendPoint[]{let cumulative=0;return MONTH_LABELS.map((label,i)=>{const month=i+1,monthClaims=claims.filter(c=>rowMonth(c)===month),submitted=sum(monthClaims.filter(c=>c.status!=="rejected"),"claim_amount"),rejected=sum(monthClaims.filter(c=>c.status==="rejected"),"claim_amount"),paid=sum(payments.filter(p=>rowMonth(p)===month),"amount_paid"),tax=sum(withholdingTax.filter(t=>rowMonth(t)===month),"tax_amount");cumulative=calculateOutstanding(cumulative+submitted+rejected,rejected,paid,tax);return {month:label,submitted:submitted/1000,paid:paid/1000,rejected:rejected/1000,withholdingTax:tax/1000,outstanding:cumulative/1000};});}
export interface InsurerPerformance{id:string;name:string;shortName:string;color:string|null;claimsCount:number;submitted:number;rejected:number;paid:number;outstanding:number;rejectionRate:number;collectionRate:number;}
export function rankInsurers(insurers:any[]=[],claims:any[]=[],payments:any[]=[],withholdingTax:any[]=[]):InsurerPerformance[]{return insurers.map(ins=>{const scoped=claims.filter(c=>c.insurance_company_id===ins.id),submitted=sum(scoped.filter(c=>c.status!=="rejected"),"claim_amount"),rejected=sum(scoped.filter(c=>c.status==="rejected"),"claim_amount"),paid=sum(payments.filter(p=>p.insurance_company_id===ins.id),"amount_paid"),tax=sum(withholdingTax.filter(t=>t.insurance_company_id===ins.id),"tax_amount"),gross=submitted+rejected,name=ins.company_name||"Unnamed";return {id:ins.id,name,shortName:name.length>14?`${name.slice(0,14)}…`:name,color:ins.color??null,claimsCount:scoped.length,submitted,rejected,paid,outstanding:calculateOutstanding(gross,rejected,paid,tax),rejectionRate:gross>0?rejected/gross*100:0,collectionRate:submitted>0?paid/submitted*100:0};}).sort((a,b)=>b.outstanding-a.outstanding||b.submitted-a.submitted);}
export function projectLinear(series:number[],periods=3):number[]{if(series.length<2)return Array(periods).fill(series[0]??0);const n=series.length,xMean=(n-1)/2,yMean=series.reduce((s,v)=>s+v,0)/n;let num=0,den=0;series.forEach((y,x)=>{num+=(x-xMean)*(y-yMean);den+=(x-xMean)**2;});const slope=den===0?0:num/den,intercept=yMean-slope*xMean;return Array.from({length:periods},(_,k)=>Math.max(0,intercept+slope*(n+k)));}
